volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/wordpress
  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/mariadb
  
networks:
    inception:
      name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wp-volume:/var/www/
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/conf/certs:/etc/nginx/ssl
    networks:
      - inception
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASS}
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

